### ISSUE TITLE
local tests error, harmony module not found

### ISSUE THREAD

**Issue by dkauf42** [podaac/l2ss-py#115]
I am trying to run `l2ss-py`'s local tests after running `poetry install`. To run the tests, I'm following the README instructions and executing `poetry run pytest -m "not aws and not integration" tests/`.  However, the following `ModuleNotFoundError` error is raised:

```
============================================= test session starts ==============================================
platform darwin -- Python 3.9.12, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/dkaufma3/projects/l2ss-py
plugins: cov-2.12.1, benchmark-3.4.1, anyio-3.5.0
collected 48 items / 1 error / 47 selected

==================================================== ERRORS ====================================================
________________________________ ERROR collecting tests/test_subset_harmony.py _________________________________
ImportError while importing test module '/Users/dkaufma3/projects/l2ss-py/tests/test_subset_harmony.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_subset_harmony.py:30: in <module>
    from podaac.subsetter.subset_harmony import L2SubsetterService
podaac/subsetter/subset_harmony.py:27: in <module>
    import harmony
E   ModuleNotFoundError: No module named 'harmony'
```

Some relevant specs:
- The l2ss-py version is 2.1.0.
- Poetry version: 1.1.14
- Python:  3.9.7

I didn't see a clear way, on the harmony GitHub, to install harmony into the local Python environment. So, **are these tests only meant to be run in a Docker container, or is there some other way one should install harmony for local tests?**  Either way, perhaps more explanation in the README would be helpful too.

**Comment by frankinspace** [comment]
Yes some more documentation around this is needed.

The structure of the l2ss-py project is such that l2ss-py can be installed as a pure python module without any dependency on harmony at all. This method of installation allows users to invoke the capability of the l2ss-py module without calling it via Harmony. To do this, the harmony dependencies are treated as optional extras (https://python-poetry.org/docs/pyproject/#extras) (https://peps.python.org/pep-0508/#extras). So in order to install everything including the extras you must do `poetry install -E harmony`.

There are a few different types of tests. The majority of them test the core functionality of l2ss-py without ever interacting with the harmony python modules. The `test_subset_harmony` tests, however, are explicitly for testing the harmony adapter layer and do require the harmony optional dependencies be installed. They could be separated better so that the harmony tests get skipped if the optional dependencies are not installed.

Anyway, the short answer to your question is, run `poetry install -E harmony` and the tests should then execute just fine in your local environment.

**Comment by dkauf42** [comment]
Thanks – that (`-E harmony`) worked!
Out of 50 tests, 49 passed and one was skipped. 42 warnings were generated.

**Comment by dkauf42** [comment]
If you'd like, @frankinspace, I can put some of this explanation into the README as a new PR for the develop branch.
